FROM scratch

MAINTAINER \
[Alexey Shabalin <shaba@altlinux.org>] \
[Gleb Fotengauer-Malinovskiy <glebfm@altlinux.org>] \
[Mikhail Gordeev <obirvalger@altlinux.org]

ADD alt-sisyphus-i586-20180925.tar.xz /

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["/bin/bash"]
